create or replace database FISCAL_DATA;

create or replace schema BRONZE;

create or replace TABLE TREASURY_DEBT (
	RECORD_DATE DATE,
	DEBT_HELD_PUBLIC_AMT NUMBER(20,2),
	INTRAGOV_HOLD_AMT NUMBER(20,2),
	TOT_PUB_DEBT_OUT_AMT NUMBER(20,2),
	SRC_LINE_NBR VARCHAR(20),
	RECORD_FISCAL_YEAR NUMBER(38,0),
	RECORD_FISCAL_QUARTER NUMBER(38,0),
	RECORD_CALENDAR_YEAR NUMBER(38,0),
	RECORD_CALENDAR_QUARTER NUMBER(38,0),
	RECORD_CALENDAR_MONTH NUMBER(38,0),
	RECORD_CALENDAR_DAY NUMBER(38,0)
);
create or replace schema GOLD;

create or replace schema PUBLIC;

create or replace schema SILVER;
